# if want to use None, use !!null
# parameters
val: true
# val: false
# firstTimeTrain: true
firstTimeTrain: false
pretrain_coarse_network: true
gan_loss_alpha: 0.2
wgan_gp_lambda: 10
coarse_l1_alpha: 1.2
l1_loss_alpha: 1.4
ae_loss_alpha: 1.0
max_delta_height: 32
max_delta_width: 32
iteration_d: 6

discount_mask: true

img_height: 256
img_width: 256
hole_height: 128
hole_width: 128
static_view_num: 30

init_lr_g: 2.0e-6
# init_lr_g: 1.0e-5
init_lr_d: 1.0e-6
batch_size: 8
coarse_iters: 2000000
total_iters: 10000000

l1_loss: true
ae_loss: true
global_wgan_loss_alpha: 1.0

spatial_discount_gamma: 0.9

compress_path_win: "E:\\TensorFlow_Learning\\Inpainting\\patch\\places\\places_train_path_win.pickle"
compress_path_linux_7810: /home/richard/TensorFlow_Learning/Inpainting/patch/places/places_train_path_linux_7810.pickle


val_path_win: "E:\\TensorFlow_Learning\\Inpainting\\patch\\places\\places_val_path_win.pickle"
val_path_linux_7810: /home/richard/TensorFlow_Learning/Inpainting/patch/places/places_val_path_linux_7810.pickle
# val_path_linux_7610: /home/icie/Datasets/celebahq_tfrecords/val

coarse_model_path_win: "E:\\TensorFlow_Learning\\Inpainting\\patch\\places\\model\\coarse"
coarse_model_path_linux_7810: /home/richard/TensorFlow_Learning/Inpainting/patch/places/model/coarse
# coarse_model_path_linux_7610: /home/icie/richard/TensorFlow_Learning/Inpainting/patch/celebahq/model/coarse

refine_model_path_win: "E:\\TensorFlow_Learning\\Inpainting\\patch\\places\\model\\refine"
refine_model_path_linux_7810: /home/richard/TensorFlow_Learning/Inpainting/patch/places/model/refine
# refine_model_path_linux_7610: /home/icie/richard/TensorFlow_Learning/Inpainting/patch/celebahq/model/refine

log_dir_win: "E:\\TensorFlow_Learning\\Inpainting\\patch\\places\\log"
log_dir_linux_7810: /home/richard/TensorFlow_Learning/Inpainting/patch/places/log
# log_dir_linux_7610: /home/icie/richard/TensorFlow_Learning/Inpainting/patch/celebahq/log