# if want to use None, use !!null

# path for windows
trainset_path_win: "E:\\TensorFlow_Learning\\Inpainting\\MPGAN\\CelebA\\celeba_train_path_win.pickle"
# events_path_win: "E:\\TensorFlow_Learning\\Inpainting\\MPGAN\\CelebA\\models_without_adv_l1\\events"
# model_path_win: "E:\\TensorFlow_Learning\\Inpainting\\MPGAN\\CelebA\\models_without_adv_l1"
model_path_win: "E:\\TensorFlow_Learning\\Inpainting\\MPGAN\\CelebA\\models_without_adv_l1_test"


# path for linux
trainset_path_linux: /home/richard/TensorFlow_Learning/Inpainting/MPGAN/CelebA/celeba_train_path_linux.pickle
events_path_linux: /home/richard/TensorFlow_Learning/Inpainting/MPGAN/CelebA/models_without_adv_l1/events    
model_path_linux: /home/richard/TensorFlow_Learning/Inpainting/MPGAN/CelebA/models_without_adv_l1

isFirstTimeTrain: true
batch_size: 16
weight_decay_rate: 1.0e-4
init_lr_g: 9.0e-4
init_lr_d: 5.0e-4
lr_decay_steps: 1000
iters_c: 30000
alpha: 0.8
