# if want to use None, use !!null
# parameters
val: false
pretrain_coarse_network: true
gan_loss_alpha: 0.001
wgan_gp_alpha: 10
coarse_l1_alpha: 1.2
l1_loss_alpha: 1.2
ae_loss_alpha: 1.2

discount_mask: true

img_height: 256
img_width: 256
hole_height: 128
hole_width: 128
batch_size: 16

l1_loss: true
ae_loss: true
global_wgan_loss_alpha: 1.0

spatial_discount_gamma: 0.9