# if want to use None, use !!null
# parameters
val: false
# val: false
# firstTimeTrain: true
firstTimeTrain: false
pretrain_coarse_network: true
gan_loss_alpha: 1.0
wgan_gp_lambda: 10
coarse_l1_alpha: 1.2
l1_loss_alpha: 1.5
ae_loss_alpha: 1.5
max_delta_height: 32
max_delta_width: 32
iteration_d: 5

discount_mask: true

img_height: 256
img_width: 256
hole_height: 128
hole_width: 128
test_hole_height: 8
test_hole_width: 8
static_view_num: 30

init_lr_g: 2.0e-6
init_lr_d: 1.0e-6
batch_size: 16
coarse_iters: 30000
total_iters: 1000000

l1_loss: true
ae_loss: true
global_wgan_loss_alpha: 0.15
local_wgan_loss_alpha: 0.15

spatial_discount_gamma: 0.9

compress_path_win: "F:\\Datasets\\celebahq_tfrecords\\train"
compress_path_linux_7810: /media/icie/b29b7268-50ad-4752-8e03-457669cab10a/celebahq_tfrecords/train
compress_path_linux_7610: /home/icie/Datasets/celebahq_tfrecords/train


val_path_win: "F:\\Datasets\\celebahq_tfrecords\\val"
val_path_linux_7810: /media/icie/b29b7268-50ad-4752-8e03-457669cab10a/celebahq_tfrecords/val
val_path_linux_7610: /home/icie/Datasets/celebahq_tfrecords/val

coarse_model_path_win: "E:\\TensorFlow_Learning\\Inpainting\\patch\\celebahq\\model\\coarse"
coarse_model_path_linux_7810: /home/richard/TensorFlow_Learning/Inpainting/patch/celebahq/model/coarse
coarse_model_path_linux_7610: /home/icie/richard/TensorFlow_Learning/Inpainting/patch/celebahq/model/coarse

refine_model_path_win: "E:\\TensorFlow_Learning\\Inpainting\\patch\\celebahq\\model\\refine"
refine_model_path_linux_7810: /home/richard/TensorFlow_Learning/Inpainting/patch/celebahq/model/refine
refine_model_path_linux_7610: /home/icie/richard/TensorFlow_Learning/Inpainting/patch/celebahq/model/refine

log_dir_win: "E:\\TensorFlow_Learning\\Inpainting\\patch\\celebahq\\log"
log_dir_linux_7810: /home/richard/TensorFlow_Learning/Inpainting/patch/celebahq/log
log_dir_linux_7610: /home/icie/richard/TensorFlow_Learning/Inpainting/patch/celebahq/log
# ADQ5MU7I6XAYTYE7IEOG7I6PSQIOSKUYM