MODEL: 1                           # 1: coarse model, 2: refine model, 3: joint model
LR: 0.0001                         # learning rate
D2G_LR: 0.1                        # discriminator/generator learning rate ratio
BETA1: 0.0                         # adam optimizer beta1
BETA2: 0.9                         # adam optimizer beta2
BATCH_SIZE: 8                      # input batch size for training
INPUT_SIZE: 256                    # input image size for training 0 for original size
MAX_ITERS: 2000000                 # maximum number of iterations to train the model
VERBOSE: 0                         # turns on verbose mode in the output console

L1_LOSS_WEIGHT: 1                  # l1 loss weight
STYLE_LOSS_WEIGHT: 1               # style loss weight
CONTENT_LOSS_WEIGHT: 1             # perceptual loss weight
ADV_LOSS_WEIGHT: 0.01              # adversarial loss weight

GAN_LOSS: "nsgan"                  # nsgan | lsgan | hinge
INIT_TYPE: "normal"                # normal | xavier | kaiming | orthogonal

FLIST_LINUX_7810: /media/icie/b29b7268-50ad-4752-8e03-457669cab10a/flist/celebahq_linux_7810.flist
LOG_DIR_LINUX_7810: /home/richard/TensorFlow_Learning/Inpainting/two_stage/celebahq/log